workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 60
    environment:
      android_env:
        - JAVA_VERSION: "17"
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
